// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package barcode.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Barcode module
	public static void aCT_Test(IContext context, barcode.proxies.BarcodeTest _barcodeTest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BarcodeTest", _barcodeTest == null ? null : _barcodeTest.getMendixObject());
		Core.microflowCall("Barcode.ACT_Test").withParams(params).execute(context);
	}
	public static barcode.proxies.BarcodeTest dS_GetBarcodeTest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Barcode.DS_GetBarcodeTest").withParams(params).execute(context);
		return result == null ? null : barcode.proxies.BarcodeTest.initialize(context, result);
	}
}
