// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Cinema module
	public static void deleteallseat(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.deleteallseat").withParams(params).execute(context);
	}
	public static system.proxies.User getUserName(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.GetUserName").withParams(params).execute(context);
		return result == null ? null : system.proxies.User.initialize(context, result);
	}
	public static void oCA_ClearAllData(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCA_ClearAllData").withParams(params).execute(context);
	}
	public static void oCA_ConfirmOrder(IContext context, cinema.proxies.transaction _transaction, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		Core.microflowCall("Cinema.OCA_ConfirmOrder").withParams(params).execute(context);
	}
	public static void oCA_CreatePPN(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCA_CreatePPN").withParams(params).execute(context);
	}
	public static void oCA_DownloadMovieTransReport(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		Core.microflowCall("Cinema.OCA_DownloadMovieTransReport").withParams(params).execute(context);
	}
	public static void oCA_DownloadTicket(IContext context, cinema.proxies.Ticket _ticket, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Ticket", _ticket == null ? null : _ticket.getMendixObject());
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OCA_DownloadTicket").withParams(params).execute(context);
	}
	public static void oCA_DownloadTransactionReport(IContext context, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OCA_DownloadTransactionReport").withParams(params).execute(context);
	}
	public static void oCA_GenerateCSVTransaction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCA_GenerateCSVTransaction").withParams(params).execute(context);
	}
	public static void oCA_GenerateMovieTransaction(IContext context, cinema.proxies.Movie _movie, cinema.proxies.movieTransactionDocument _movieTransactionDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		params.put("movieTransactionDocument", _movieTransactionDocument == null ? null : _movieTransactionDocument.getMendixObject());
		Core.microflowCall("Cinema.OCA_GenerateMovieTransaction").withParams(params).execute(context);
	}
	public static void oCA_GeneratePDFTransaction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCA_GeneratePDFTransaction").withParams(params).execute(context);
	}
	public static void oCA_GenerateTransactionTimelineReport(IContext context, cinema.proxies.TransactionTimeline _transactionTimeline)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TransactionTimeline", _transactionTimeline == null ? null : _transactionTimeline.getMendixObject());
		Core.microflowCall("Cinema.OCA_GenerateTransactionTimelineReport").withParams(params).execute(context);
	}
	public static void oCA_GetMovieTrailer(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		Core.microflowCall("Cinema.OCA_GetMovieTrailer").withParams(params).execute(context);
	}
	public static void oCA_OpenLoginPage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCA_OpenLoginPage").withParams(params).execute(context);
	}
	public static void oCA_SaveNewPPN(IContext context, cinema.proxies.PPN _pPN)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PPN", _pPN == null ? null : _pPN.getMendixObject());
		Core.microflowCall("Cinema.OCA_SaveNewPPN").withParams(params).execute(context);
	}
	public static void oCA_SaveScheduleandPrice(IContext context, cinema.proxies.Price _price)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Price", _price == null ? null : _price.getMendixObject());
		Core.microflowCall("Cinema.OCA_SaveScheduleandPrice").withParams(params).execute(context);
	}
	public static void oCA_Schedule_Cinema(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		Core.microflowCall("Cinema.OCA_Schedule_Cinema").withParams(params).execute(context);
	}
	public static cinema.proxies.TheatreSeatHelper oCA_SelectedSeat(IContext context, cinema.proxies.TheatreSeatHelper _theatreSeatHelper, cinema.proxies.TeatherRow _teatherRow, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TheatreSeatHelper", _theatreSeatHelper == null ? null : _theatreSeatHelper.getMendixObject());
		params.put("TeatherRow", _teatherRow == null ? null : _teatherRow.getMendixObject());
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.OCA_SelectedSeat").withParams(params).execute(context);
		return result == null ? null : cinema.proxies.TheatreSeatHelper.initialize(context, result);
	}
	public static void oCA_TransactionPageBasedOnStatus(IContext context, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OCA_TransactionPageBasedOnStatus").withParams(params).execute(context);
	}
	public static void oCA_UserConfirmPayment(IContext context, cinema.proxies.transaction _transaction, cinema.proxies.PaymentActivity _paymentActivity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		params.put("PaymentActivity", _paymentActivity == null ? null : _paymentActivity.getMendixObject());
		Core.microflowCall("Cinema.OCA_UserConfirmPayment").withParams(params).execute(context);
	}
	public static void oCA_UserPayTransaction(IContext context, cinema.proxies.PaymentActivity _paymentActivity, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("PaymentActivity", _paymentActivity == null ? null : _paymentActivity.getMendixObject());
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OCA_UserPayTransaction").withParams(params).execute(context);
	}
	public static void oCA_ViewAllSelectedSeat(IContext context, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		Core.microflowCall("Cinema.OCA_ViewAllSelectedSeat").withParams(params).execute(context);
	}
	public static void oCA_WaitingPayment(IContext context, cinema.proxies.transaction _transaction, cinema.proxies.PaymentMethod _paymentMethod)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		params.put("PaymentMethod", _paymentMethod == null ? null : _paymentMethod.getMendixObject());
		Core.microflowCall("Cinema.OCA_WaitingPayment").withParams(params).execute(context);
	}
	public static void oCE_GetMoviePlaying(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OCE_GetMoviePlaying").withParams(params).execute(context);
	}
	public static void oCE_MovieDescription(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		Core.microflowCall("Cinema.OCE_MovieDescription").withParams(params).execute(context);
	}
	public static void oCE_SaveMovieSchedule(IContext context, cinema.proxies.Cinema _cinemaSchedule)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CinemaSchedule", _cinemaSchedule == null ? null : _cinemaSchedule.getMendixObject());
		Core.microflowCall("Cinema.OCE_SaveMovieSchedule").withParams(params).execute(context);
	}
	public static void oCE_ValidationSeatInput(IContext context, cinema.proxies.Theatre _theatre)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Theatre", _theatre == null ? null : _theatre.getMendixObject());
		Core.microflowCall("Cinema.OCE_ValidationSeatInput").withParams(params).execute(context);
	}
	public static void oEA_AutoGeneratedSeat(IContext context, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		Core.microflowCall("Cinema.OEA_AutoGeneratedSeat").withParams(params).execute(context);
	}
	public static void oEA_CancelTransaction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OEA_CancelTransaction").withParams(params).execute(context);
	}
	public static void oEA_CSVTransactionFile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OEA_CSVTransactionFile").withParams(params).execute(context);
	}
	public static void oEA_FinishTransaction(IContext context, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OEA_FinishTransaction").withParams(params).execute(context);
	}
	public static java.util.List<cinema.proxies.transaction> oEA_GetMovieChartData(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetMovieChartData").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.transaction.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.Movie> oEA_GetMovieTransaction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetMovieTransaction").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Movie.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static cinema.proxies.movieTransactionDocument oEA_GetMovieTransDoc(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.OEA_GetMovieTransDoc").withParams(params).execute(context);
		return result == null ? null : cinema.proxies.movieTransactionDocument.initialize(context, result);
	}
	public static cinema.proxies.PPN oEA_GetPPN(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.OEA_GetPPN").withParams(params).execute(context);
		return result == null ? null : cinema.proxies.PPN.initialize(context, result);
	}
	public static java.util.List<cinema.proxies.TheatreSeatHelper> oEA_GetRetrieveSelectedSeat(IContext context, cinema.proxies.Cinema _cinema, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetRetrieveSelectedSeat").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.TheatreSeatHelper.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.TheatreSeatHelper> oEA_GetSeatNumberCinema(IContext context, cinema.proxies.TeatherRow _teatherRow, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TeatherRow", _teatherRow == null ? null : _teatherRow.getMendixObject());
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetSeatNumberCinema").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.TheatreSeatHelper.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.TeatherRow> oEA_GetSeatRowCinema(IContext context, cinema.proxies.Cinema _cinema)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetSeatRowCinema").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.TeatherRow.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.Cinema> oEA_GetTimeDateCinema(IContext context, cinema.proxies.Cinema _cinema, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Cinema", _cinema == null ? null : _cinema.getMendixObject());
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetTimeDateCinema").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Cinema.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.transaction> oEA_GetUserTransactionHistory(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_GetUserTransactionHistory").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.transaction.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.Cinema> oEA_ListSchedulebyDate(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_ListSchedulebyDate").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Cinema.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.transaction> oEA_MovieTranList(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEA_MovieTranList").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.transaction.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void oEA_SaveSelectedSeat(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OEA_SaveSelectedSeat").withParams(params).execute(context);
	}
	public static void oEA_TimePaymentisUp(IContext context, cinema.proxies.transaction _transaction)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("transaction", _transaction == null ? null : _transaction.getMendixObject());
		Core.microflowCall("Cinema.OEA_TimePaymentisUp").withParams(params).execute(context);
	}
	public static boolean oEM_CheckaisStoredisSchedule(IContext context, cinema.proxies.Cinema _cinemaSchedule)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CinemaSchedule", _cinemaSchedule == null ? null : _cinemaSchedule.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Cinema.OEM_CheckaisStoredisSchedule").withParams(params).execute(context);
	}
	public static cinema.proxies.ImportActivity oEN_GetDateTimeLastImport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.OEN_GetDateTimeLastImport").withParams(params).execute(context);
		return result == null ? null : cinema.proxies.ImportActivity.initialize(context, result);
	}
	public static java.util.List<cinema.proxies.Cast> oEN_GetMovieCast(IContext context, cinema.proxies.Movie _movie)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Movie", _movie == null ? null : _movie.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEN_GetMovieCast").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Cast.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.Movie> oEN_GetMoviePlaying(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEN_GetMoviePlaying").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Movie.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static java.util.List<cinema.proxies.Movie> oEN_GetUpcomingMovie(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Cinema.OEN_GetUpcomingMovie").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> cinema.proxies.Movie.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static cinema.proxies.Cinema oEN_RetrievestartTime(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Cinema.OEN_RetrievestartTime").withParams(params).execute(context);
		return result == null ? null : cinema.proxies.Cinema.initialize(context, result);
	}
	public static void oSE_DeleteUnpaymentTransaction(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.OSE_DeleteUnpaymentTransaction").withParams(params).execute(context);
	}
	public static void ticket__DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.Ticket__DeleteAll").withParams(params).execute(context);
	}
	public static void transaction_DeleteAll(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Cinema.Transaction_DeleteAll").withParams(params).execute(context);
	}
}
