// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class MovieVideo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject movieVideoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.MovieVideo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TMDB_ID("TMDB_ID"),
		Name("Name"),
		site("site"),
		key("key"),
		isOfficial("isOfficial"),
		TypeVideo("TypeVideo"),
		MovieVideo_Movie("Cinema.MovieVideo_Movie");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MovieVideo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MovieVideo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject movieVideoMendixObject)
	{
		if (movieVideoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, movieVideoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.movieVideoMendixObject = movieVideoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MovieVideo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.MovieVideo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.MovieVideo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.MovieVideo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.MovieVideo(context, mendixObject);
	}

	public static cinema.proxies.MovieVideo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.MovieVideo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TMDB_ID
	 */
	public final java.lang.Integer getTMDB_ID()
	{
		return getTMDB_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of TMDB_ID
	 */
	public final java.lang.Integer getTMDB_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TMDB_ID.toString());
	}

	/**
	 * Set value of TMDB_ID
	 * @param tmdb_id
	 */
	public final void setTMDB_ID(java.lang.Integer tmdb_id)
	{
		setTMDB_ID(getContext(), tmdb_id);
	}

	/**
	 * Set value of TMDB_ID
	 * @param context
	 * @param tmdb_id
	 */
	public final void setTMDB_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tmdb_id)
	{
		getMendixObject().setValue(context, MemberNames.TMDB_ID.toString(), tmdb_id);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of site
	 */
	public final java.lang.String getsite()
	{
		return getsite(getContext());
	}

	/**
	 * @param context
	 * @return value of site
	 */
	public final java.lang.String getsite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.site.toString());
	}

	/**
	 * Set value of site
	 * @param site
	 */
	public final void setsite(java.lang.String site)
	{
		setsite(getContext(), site);
	}

	/**
	 * Set value of site
	 * @param context
	 * @param site
	 */
	public final void setsite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String site)
	{
		getMendixObject().setValue(context, MemberNames.site.toString(), site);
	}

	/**
	 * @return value of key
	 */
	public final java.lang.String getkey()
	{
		return getkey(getContext());
	}

	/**
	 * @param context
	 * @return value of key
	 */
	public final java.lang.String getkey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.key.toString());
	}

	/**
	 * Set value of key
	 * @param key
	 */
	public final void setkey(java.lang.String key)
	{
		setkey(getContext(), key);
	}

	/**
	 * Set value of key
	 * @param context
	 * @param key
	 */
	public final void setkey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.key.toString(), key);
	}

	/**
	 * @return value of isOfficial
	 */
	public final java.lang.Boolean getisOfficial()
	{
		return getisOfficial(getContext());
	}

	/**
	 * @param context
	 * @return value of isOfficial
	 */
	public final java.lang.Boolean getisOfficial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isOfficial.toString());
	}

	/**
	 * Set value of isOfficial
	 * @param isofficial
	 */
	public final void setisOfficial(java.lang.Boolean isofficial)
	{
		setisOfficial(getContext(), isofficial);
	}

	/**
	 * Set value of isOfficial
	 * @param context
	 * @param isofficial
	 */
	public final void setisOfficial(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isofficial)
	{
		getMendixObject().setValue(context, MemberNames.isOfficial.toString(), isofficial);
	}

	/**
	 * @return value of TypeVideo
	 */
	public final java.lang.String getTypeVideo()
	{
		return getTypeVideo(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeVideo
	 */
	public final java.lang.String getTypeVideo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TypeVideo.toString());
	}

	/**
	 * Set value of TypeVideo
	 * @param typevideo
	 */
	public final void setTypeVideo(java.lang.String typevideo)
	{
		setTypeVideo(getContext(), typevideo);
	}

	/**
	 * Set value of TypeVideo
	 * @param context
	 * @param typevideo
	 */
	public final void setTypeVideo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String typevideo)
	{
		getMendixObject().setValue(context, MemberNames.TypeVideo.toString(), typevideo);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MovieVideo_Movie
	 */
	public final cinema.proxies.Movie getMovieVideo_Movie() throws com.mendix.core.CoreException
	{
		return getMovieVideo_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of MovieVideo_Movie
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.Movie getMovieVideo_Movie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.Movie result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MovieVideo_Movie.toString());
		if (identifier != null) {
			result = cinema.proxies.Movie.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MovieVideo_Movie
	 * @param movievideo_movie
	 */
	public final void setMovieVideo_Movie(cinema.proxies.Movie movievideo_movie)
	{
		setMovieVideo_Movie(getContext(), movievideo_movie);
	}

	/**
	 * Set value of MovieVideo_Movie
	 * @param context
	 * @param movievideo_movie
	 */
	public final void setMovieVideo_Movie(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Movie movievideo_movie)
	{
		if (movievideo_movie == null) {
			getMendixObject().setValue(context, MemberNames.MovieVideo_Movie.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MovieVideo_Movie.toString(), movievideo_movie.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return movieVideoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.MovieVideo that = (cinema.proxies.MovieVideo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
