// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class Movie
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject movieMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.Movie";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TMDB_ID("TMDB_ID"),
		MovieCode("MovieCode"),
		Title("Title"),
		Description("Description"),
		PosterPath("PosterPath"),
		BackdropPath("BackdropPath"),
		isAdult("isAdult"),
		Popularity("Popularity"),
		Runtime("Runtime"),
		YoutubeKey("YoutubeKey"),
		Type_Movie("Type_Movie"),
		ReleasedDate("ReleasedDate"),
		vote_average("vote_average"),
		movieTransactionDocument_Movie("Cinema.movieTransactionDocument_Movie"),
		MovieImage_Movie("Cinema.MovieImage_Movie");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Movie(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Movie(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject movieMendixObject)
	{
		if (movieMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, movieMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.movieMendixObject = movieMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Movie.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.Movie initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.Movie.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.Movie initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.Movie(context, mendixObject);
	}

	public static cinema.proxies.Movie load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.Movie.initialize(context, mendixObject);
	}

	public static java.util.List<cinema.proxies.Movie> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cinema.proxies.Movie.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TMDB_ID
	 */
	public final java.lang.Integer getTMDB_ID()
	{
		return getTMDB_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of TMDB_ID
	 */
	public final java.lang.Integer getTMDB_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TMDB_ID.toString());
	}

	/**
	 * Set value of TMDB_ID
	 * @param tmdb_id
	 */
	public final void setTMDB_ID(java.lang.Integer tmdb_id)
	{
		setTMDB_ID(getContext(), tmdb_id);
	}

	/**
	 * Set value of TMDB_ID
	 * @param context
	 * @param tmdb_id
	 */
	public final void setTMDB_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tmdb_id)
	{
		getMendixObject().setValue(context, MemberNames.TMDB_ID.toString(), tmdb_id);
	}

	/**
	 * @return value of MovieCode
	 */
	public final java.lang.String getMovieCode()
	{
		return getMovieCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MovieCode
	 */
	public final java.lang.String getMovieCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MovieCode.toString());
	}

	/**
	 * Set value of MovieCode
	 * @param moviecode
	 */
	public final void setMovieCode(java.lang.String moviecode)
	{
		setMovieCode(getContext(), moviecode);
	}

	/**
	 * Set value of MovieCode
	 * @param context
	 * @param moviecode
	 */
	public final void setMovieCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String moviecode)
	{
		getMendixObject().setValue(context, MemberNames.MovieCode.toString(), moviecode);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of PosterPath
	 */
	public final java.lang.String getPosterPath()
	{
		return getPosterPath(getContext());
	}

	/**
	 * @param context
	 * @return value of PosterPath
	 */
	public final java.lang.String getPosterPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PosterPath.toString());
	}

	/**
	 * Set value of PosterPath
	 * @param posterpath
	 */
	public final void setPosterPath(java.lang.String posterpath)
	{
		setPosterPath(getContext(), posterpath);
	}

	/**
	 * Set value of PosterPath
	 * @param context
	 * @param posterpath
	 */
	public final void setPosterPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String posterpath)
	{
		getMendixObject().setValue(context, MemberNames.PosterPath.toString(), posterpath);
	}

	/**
	 * @return value of BackdropPath
	 */
	public final java.lang.String getBackdropPath()
	{
		return getBackdropPath(getContext());
	}

	/**
	 * @param context
	 * @return value of BackdropPath
	 */
	public final java.lang.String getBackdropPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BackdropPath.toString());
	}

	/**
	 * Set value of BackdropPath
	 * @param backdroppath
	 */
	public final void setBackdropPath(java.lang.String backdroppath)
	{
		setBackdropPath(getContext(), backdroppath);
	}

	/**
	 * Set value of BackdropPath
	 * @param context
	 * @param backdroppath
	 */
	public final void setBackdropPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String backdroppath)
	{
		getMendixObject().setValue(context, MemberNames.BackdropPath.toString(), backdroppath);
	}

	/**
	 * @return value of isAdult
	 */
	public final java.lang.Boolean getisAdult()
	{
		return getisAdult(getContext());
	}

	/**
	 * @param context
	 * @return value of isAdult
	 */
	public final java.lang.Boolean getisAdult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isAdult.toString());
	}

	/**
	 * Set value of isAdult
	 * @param isadult
	 */
	public final void setisAdult(java.lang.Boolean isadult)
	{
		setisAdult(getContext(), isadult);
	}

	/**
	 * Set value of isAdult
	 * @param context
	 * @param isadult
	 */
	public final void setisAdult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isadult)
	{
		getMendixObject().setValue(context, MemberNames.isAdult.toString(), isadult);
	}

	/**
	 * @return value of Popularity
	 */
	public final java.lang.String getPopularity()
	{
		return getPopularity(getContext());
	}

	/**
	 * @param context
	 * @return value of Popularity
	 */
	public final java.lang.String getPopularity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Popularity.toString());
	}

	/**
	 * Set value of Popularity
	 * @param popularity
	 */
	public final void setPopularity(java.lang.String popularity)
	{
		setPopularity(getContext(), popularity);
	}

	/**
	 * Set value of Popularity
	 * @param context
	 * @param popularity
	 */
	public final void setPopularity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String popularity)
	{
		getMendixObject().setValue(context, MemberNames.Popularity.toString(), popularity);
	}

	/**
	 * @return value of Runtime
	 */
	public final java.lang.Integer getRuntime()
	{
		return getRuntime(getContext());
	}

	/**
	 * @param context
	 * @return value of Runtime
	 */
	public final java.lang.Integer getRuntime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Runtime.toString());
	}

	/**
	 * Set value of Runtime
	 * @param runtime
	 */
	public final void setRuntime(java.lang.Integer runtime)
	{
		setRuntime(getContext(), runtime);
	}

	/**
	 * Set value of Runtime
	 * @param context
	 * @param runtime
	 */
	public final void setRuntime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer runtime)
	{
		getMendixObject().setValue(context, MemberNames.Runtime.toString(), runtime);
	}

	/**
	 * @return value of YoutubeKey
	 */
	public final java.lang.String getYoutubeKey()
	{
		return getYoutubeKey(getContext());
	}

	/**
	 * @param context
	 * @return value of YoutubeKey
	 */
	public final java.lang.String getYoutubeKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.YoutubeKey.toString());
	}

	/**
	 * Set value of YoutubeKey
	 * @param youtubekey
	 */
	public final void setYoutubeKey(java.lang.String youtubekey)
	{
		setYoutubeKey(getContext(), youtubekey);
	}

	/**
	 * Set value of YoutubeKey
	 * @param context
	 * @param youtubekey
	 */
	public final void setYoutubeKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String youtubekey)
	{
		getMendixObject().setValue(context, MemberNames.YoutubeKey.toString(), youtubekey);
	}

	/**
	 * Set value of Type_Movie
	 * @param type_movie
	 */
	public final cinema.proxies.Enum_TypeMovie getType_Movie()
	{
		return getType_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of Type_Movie
	 */
	public final cinema.proxies.Enum_TypeMovie getType_Movie(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Type_Movie.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.Enum_TypeMovie.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Type_Movie
	 * @param type_movie
	 */
	public final void setType_Movie(cinema.proxies.Enum_TypeMovie type_movie)
	{
		setType_Movie(getContext(), type_movie);
	}

	/**
	 * Set value of Type_Movie
	 * @param context
	 * @param type_movie
	 */
	public final void setType_Movie(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Enum_TypeMovie type_movie)
	{
		if (type_movie != null) {
			getMendixObject().setValue(context, MemberNames.Type_Movie.toString(), type_movie.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Type_Movie.toString(), null);
		}
	}

	/**
	 * @return value of ReleasedDate
	 */
	public final java.lang.String getReleasedDate()
	{
		return getReleasedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ReleasedDate
	 */
	public final java.lang.String getReleasedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReleasedDate.toString());
	}

	/**
	 * Set value of ReleasedDate
	 * @param releaseddate
	 */
	public final void setReleasedDate(java.lang.String releaseddate)
	{
		setReleasedDate(getContext(), releaseddate);
	}

	/**
	 * Set value of ReleasedDate
	 * @param context
	 * @param releaseddate
	 */
	public final void setReleasedDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String releaseddate)
	{
		getMendixObject().setValue(context, MemberNames.ReleasedDate.toString(), releaseddate);
	}

	/**
	 * @return value of vote_average
	 */
	public final java.math.BigDecimal getvote_average()
	{
		return getvote_average(getContext());
	}

	/**
	 * @param context
	 * @return value of vote_average
	 */
	public final java.math.BigDecimal getvote_average(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.vote_average.toString());
	}

	/**
	 * Set value of vote_average
	 * @param vote_average
	 */
	public final void setvote_average(java.math.BigDecimal vote_average)
	{
		setvote_average(getContext(), vote_average);
	}

	/**
	 * Set value of vote_average
	 * @param context
	 * @param vote_average
	 */
	public final void setvote_average(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal vote_average)
	{
		getMendixObject().setValue(context, MemberNames.vote_average.toString(), vote_average);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of movieTransactionDocument_Movie
	 */
	public final cinema.proxies.movieTransactionDocument getmovieTransactionDocument_Movie() throws com.mendix.core.CoreException
	{
		return getmovieTransactionDocument_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of movieTransactionDocument_Movie
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.movieTransactionDocument getmovieTransactionDocument_Movie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.movieTransactionDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.movieTransactionDocument_Movie.toString());
		if (identifier != null) {
			result = cinema.proxies.movieTransactionDocument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of movieTransactionDocument_Movie
	 * @param movietransactiondocument_movie
	 */
	public final void setmovieTransactionDocument_Movie(cinema.proxies.movieTransactionDocument movietransactiondocument_movie)
	{
		setmovieTransactionDocument_Movie(getContext(), movietransactiondocument_movie);
	}

	/**
	 * Set value of movieTransactionDocument_Movie
	 * @param context
	 * @param movietransactiondocument_movie
	 */
	public final void setmovieTransactionDocument_Movie(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.movieTransactionDocument movietransactiondocument_movie)
	{
		if (movietransactiondocument_movie == null) {
			getMendixObject().setValue(context, MemberNames.movieTransactionDocument_Movie.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.movieTransactionDocument_Movie.toString(), movietransactiondocument_movie.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MovieImage_Movie
	 */
	public final cinema.proxies.MovieImage getMovieImage_Movie() throws com.mendix.core.CoreException
	{
		return getMovieImage_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of MovieImage_Movie
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.MovieImage getMovieImage_Movie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.MovieImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MovieImage_Movie.toString());
		if (identifier != null) {
			result = cinema.proxies.MovieImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MovieImage_Movie
	 * @param movieimage_movie
	 */
	public final void setMovieImage_Movie(cinema.proxies.MovieImage movieimage_movie)
	{
		setMovieImage_Movie(getContext(), movieimage_movie);
	}

	/**
	 * Set value of MovieImage_Movie
	 * @param context
	 * @param movieimage_movie
	 */
	public final void setMovieImage_Movie(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.MovieImage movieimage_movie)
	{
		if (movieimage_movie == null) {
			getMendixObject().setValue(context, MemberNames.MovieImage_Movie.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MovieImage_Movie.toString(), movieimage_movie.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return movieMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.Movie that = (cinema.proxies.Movie) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
