// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class TheatreSeat
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject theatreSeatMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.TheatreSeat";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		status("status"),
		row("row"),
		number("number"),
		TheatreSeat_Cinema("Cinema.TheatreSeat_Cinema");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject theatreSeatMendixObject)
	{
		if (theatreSeatMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, theatreSeatMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.theatreSeatMendixObject = theatreSeatMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TheatreSeat.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.TheatreSeat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.TheatreSeat.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.TheatreSeat initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.TheatreSeat(context, mendixObject);
	}

	public static cinema.proxies.TheatreSeat load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.TheatreSeat.initialize(context, mendixObject);
	}

	public static java.util.List<cinema.proxies.TheatreSeat> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cinema.proxies.TheatreSeat.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of status
	 * @param status
	 */
	public final cinema.proxies.enum_StatusTheatreSeat getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final cinema.proxies.enum_StatusTheatreSeat getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.status.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.enum_StatusTheatreSeat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(cinema.proxies.enum_StatusTheatreSeat status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.enum_StatusTheatreSeat status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.status.toString(), null);
		}
	}

	/**
	 * @return value of row
	 */
	public final java.lang.String getrow()
	{
		return getrow(getContext());
	}

	/**
	 * @param context
	 * @return value of row
	 */
	public final java.lang.String getrow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.row.toString());
	}

	/**
	 * Set value of row
	 * @param row
	 */
	public final void setrow(java.lang.String row)
	{
		setrow(getContext(), row);
	}

	/**
	 * Set value of row
	 * @param context
	 * @param row
	 */
	public final void setrow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String row)
	{
		getMendixObject().setValue(context, MemberNames.row.toString(), row);
	}

	/**
	 * @return value of number
	 */
	public final java.lang.Integer getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.lang.Integer getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.lang.Integer number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TheatreSeat_Cinema
	 */
	public final cinema.proxies.Cinema getTheatreSeat_Cinema() throws com.mendix.core.CoreException
	{
		return getTheatreSeat_Cinema(getContext());
	}

	/**
	 * @param context
	 * @return value of TheatreSeat_Cinema
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.Cinema getTheatreSeat_Cinema(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.Cinema result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TheatreSeat_Cinema.toString());
		if (identifier != null) {
			result = cinema.proxies.Cinema.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TheatreSeat_Cinema
	 * @param theatreseat_cinema
	 */
	public final void setTheatreSeat_Cinema(cinema.proxies.Cinema theatreseat_cinema)
	{
		setTheatreSeat_Cinema(getContext(), theatreseat_cinema);
	}

	/**
	 * Set value of TheatreSeat_Cinema
	 * @param context
	 * @param theatreseat_cinema
	 */
	public final void setTheatreSeat_Cinema(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Cinema theatreseat_cinema)
	{
		if (theatreseat_cinema == null) {
			getMendixObject().setValue(context, MemberNames.TheatreSeat_Cinema.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TheatreSeat_Cinema.toString(), theatreseat_cinema.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return theatreSeatMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.TheatreSeat that = (cinema.proxies.TheatreSeat) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
