// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class TheatreSeatHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject theatreSeatHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.TheatreSeatHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		isSelected("isSelected"),
		status("status"),
		Row("Row"),
		number("number"),
		TheatreSeatHelper_TheatreSeat("Cinema.TheatreSeatHelper_TheatreSeat"),
		TheatreSeatHelper_Cinema("Cinema.TheatreSeatHelper_Cinema");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TheatreSeatHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TheatreSeatHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject theatreSeatHelperMendixObject)
	{
		if (theatreSeatHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, theatreSeatHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.theatreSeatHelperMendixObject = theatreSeatHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TheatreSeatHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.TheatreSeatHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.TheatreSeatHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.TheatreSeatHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.TheatreSeatHelper(context, mendixObject);
	}

	public static cinema.proxies.TheatreSeatHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.TheatreSeatHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of isSelected
	 */
	public final java.lang.Boolean getisSelected()
	{
		return getisSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of isSelected
	 */
	public final java.lang.Boolean getisSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isSelected.toString());
	}

	/**
	 * Set value of isSelected
	 * @param isselected
	 */
	public final void setisSelected(java.lang.Boolean isselected)
	{
		setisSelected(getContext(), isselected);
	}

	/**
	 * Set value of isSelected
	 * @param context
	 * @param isselected
	 */
	public final void setisSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isselected)
	{
		getMendixObject().setValue(context, MemberNames.isSelected.toString(), isselected);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final cinema.proxies.enum_StatusTheatreSeat getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final cinema.proxies.enum_StatusTheatreSeat getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.status.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.enum_StatusTheatreSeat.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(cinema.proxies.enum_StatusTheatreSeat status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.enum_StatusTheatreSeat status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.status.toString(), null);
		}
	}

	/**
	 * @return value of Row
	 */
	public final java.lang.String getRow()
	{
		return getRow(getContext());
	}

	/**
	 * @param context
	 * @return value of Row
	 */
	public final java.lang.String getRow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Row.toString());
	}

	/**
	 * Set value of Row
	 * @param row
	 */
	public final void setRow(java.lang.String row)
	{
		setRow(getContext(), row);
	}

	/**
	 * Set value of Row
	 * @param context
	 * @param row
	 */
	public final void setRow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String row)
	{
		getMendixObject().setValue(context, MemberNames.Row.toString(), row);
	}

	/**
	 * @return value of number
	 */
	public final java.lang.Integer getnumber()
	{
		return getnumber(getContext());
	}

	/**
	 * @param context
	 * @return value of number
	 */
	public final java.lang.Integer getnumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.number.toString());
	}

	/**
	 * Set value of number
	 * @param number
	 */
	public final void setnumber(java.lang.Integer number)
	{
		setnumber(getContext(), number);
	}

	/**
	 * Set value of number
	 * @param context
	 * @param number
	 */
	public final void setnumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer number)
	{
		getMendixObject().setValue(context, MemberNames.number.toString(), number);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TheatreSeatHelper_TheatreSeat
	 */
	public final cinema.proxies.TheatreSeat getTheatreSeatHelper_TheatreSeat() throws com.mendix.core.CoreException
	{
		return getTheatreSeatHelper_TheatreSeat(getContext());
	}

	/**
	 * @param context
	 * @return value of TheatreSeatHelper_TheatreSeat
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.TheatreSeat getTheatreSeatHelper_TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.TheatreSeat result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TheatreSeatHelper_TheatreSeat.toString());
		if (identifier != null) {
			result = cinema.proxies.TheatreSeat.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TheatreSeatHelper_TheatreSeat
	 * @param theatreseathelper_theatreseat
	 */
	public final void setTheatreSeatHelper_TheatreSeat(cinema.proxies.TheatreSeat theatreseathelper_theatreseat)
	{
		setTheatreSeatHelper_TheatreSeat(getContext(), theatreseathelper_theatreseat);
	}

	/**
	 * Set value of TheatreSeatHelper_TheatreSeat
	 * @param context
	 * @param theatreseathelper_theatreseat
	 */
	public final void setTheatreSeatHelper_TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.TheatreSeat theatreseathelper_theatreseat)
	{
		if (theatreseathelper_theatreseat == null) {
			getMendixObject().setValue(context, MemberNames.TheatreSeatHelper_TheatreSeat.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TheatreSeatHelper_TheatreSeat.toString(), theatreseathelper_theatreseat.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TheatreSeatHelper_Cinema
	 */
	public final cinema.proxies.Cinema getTheatreSeatHelper_Cinema() throws com.mendix.core.CoreException
	{
		return getTheatreSeatHelper_Cinema(getContext());
	}

	/**
	 * @param context
	 * @return value of TheatreSeatHelper_Cinema
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.Cinema getTheatreSeatHelper_Cinema(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.Cinema result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TheatreSeatHelper_Cinema.toString());
		if (identifier != null) {
			result = cinema.proxies.Cinema.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TheatreSeatHelper_Cinema
	 * @param theatreseathelper_cinema
	 */
	public final void setTheatreSeatHelper_Cinema(cinema.proxies.Cinema theatreseathelper_cinema)
	{
		setTheatreSeatHelper_Cinema(getContext(), theatreseathelper_cinema);
	}

	/**
	 * Set value of TheatreSeatHelper_Cinema
	 * @param context
	 * @param theatreseathelper_cinema
	 */
	public final void setTheatreSeatHelper_Cinema(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Cinema theatreseathelper_cinema)
	{
		if (theatreseathelper_cinema == null) {
			getMendixObject().setValue(context, MemberNames.TheatreSeatHelper_Cinema.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TheatreSeatHelper_Cinema.toString(), theatreseathelper_cinema.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return theatreSeatHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.TheatreSeatHelper that = (cinema.proxies.TheatreSeatHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
