// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class Ticket extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.Ticket";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Ticket_transaction("Cinema.Ticket_transaction"),
		Ticket_TheatreSeat("Cinema.Ticket_TheatreSeat"),
		TicketDocument_Ticket("Cinema.TicketDocument_Ticket");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ticket(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ticket(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ticketMendixObject)
	{
		super(context, ticketMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, ticketMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Ticket.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.Ticket initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.Ticket.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.Ticket initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.Ticket(context, mendixObject);
	}

	public static cinema.proxies.Ticket load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.Ticket.initialize(context, mendixObject);
	}

	public static java.util.List<cinema.proxies.Ticket> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cinema.proxies.Ticket.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ticket_transaction
	 */
	public final cinema.proxies.transaction getTicket_transaction() throws com.mendix.core.CoreException
	{
		return getTicket_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of Ticket_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.transaction getTicket_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ticket_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.transaction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ticket_transaction
	 * @param ticket_transaction
	 */
	public final void setTicket_transaction(cinema.proxies.transaction ticket_transaction)
	{
		setTicket_transaction(getContext(), ticket_transaction);
	}

	/**
	 * Set value of Ticket_transaction
	 * @param context
	 * @param ticket_transaction
	 */
	public final void setTicket_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.transaction ticket_transaction)
	{
		if (ticket_transaction == null) {
			getMendixObject().setValue(context, MemberNames.Ticket_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ticket_transaction.toString(), ticket_transaction.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Ticket_TheatreSeat
	 */
	public final cinema.proxies.TheatreSeat getTicket_TheatreSeat() throws com.mendix.core.CoreException
	{
		return getTicket_TheatreSeat(getContext());
	}

	/**
	 * @param context
	 * @return value of Ticket_TheatreSeat
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.TheatreSeat getTicket_TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.TheatreSeat result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Ticket_TheatreSeat.toString());
		if (identifier != null) {
			result = cinema.proxies.TheatreSeat.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Ticket_TheatreSeat
	 * @param ticket_theatreseat
	 */
	public final void setTicket_TheatreSeat(cinema.proxies.TheatreSeat ticket_theatreseat)
	{
		setTicket_TheatreSeat(getContext(), ticket_theatreseat);
	}

	/**
	 * Set value of Ticket_TheatreSeat
	 * @param context
	 * @param ticket_theatreseat
	 */
	public final void setTicket_TheatreSeat(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.TheatreSeat ticket_theatreseat)
	{
		if (ticket_theatreseat == null) {
			getMendixObject().setValue(context, MemberNames.Ticket_TheatreSeat.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Ticket_TheatreSeat.toString(), ticket_theatreseat.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TicketDocument_Ticket
	 */
	public final cinema.proxies.TicketDocument getTicketDocument_Ticket() throws com.mendix.core.CoreException
	{
		return getTicketDocument_Ticket(getContext());
	}

	/**
	 * @param context
	 * @return value of TicketDocument_Ticket
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.TicketDocument getTicketDocument_Ticket(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.TicketDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TicketDocument_Ticket.toString());
		if (identifier != null) {
			result = cinema.proxies.TicketDocument.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TicketDocument_Ticket
	 * @param ticketdocument_ticket
	 */
	public final void setTicketDocument_Ticket(cinema.proxies.TicketDocument ticketdocument_ticket)
	{
		setTicketDocument_Ticket(getContext(), ticketdocument_ticket);
	}

	/**
	 * Set value of TicketDocument_Ticket
	 * @param context
	 * @param ticketdocument_ticket
	 */
	public final void setTicketDocument_Ticket(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.TicketDocument ticketdocument_ticket)
	{
		if (ticketdocument_ticket == null) {
			getMendixObject().setValue(context, MemberNames.TicketDocument_Ticket.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TicketDocument_Ticket.toString(), ticketdocument_ticket.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.Ticket that = (cinema.proxies.Ticket) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
