// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class Total_Transaction
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject total_TransactionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.Total_Transaction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		sum("sum"),
		Total_Transaction_transaction("Cinema.Total_Transaction_transaction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Total_Transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Total_Transaction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject total_TransactionMendixObject)
	{
		if (total_TransactionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, total_TransactionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.total_TransactionMendixObject = total_TransactionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Total_Transaction.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.Total_Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.Total_Transaction.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.Total_Transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.Total_Transaction(context, mendixObject);
	}

	public static cinema.proxies.Total_Transaction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.Total_Transaction.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of sum
	 */
	public final java.lang.Integer getsum()
	{
		return getsum(getContext());
	}

	/**
	 * @param context
	 * @return value of sum
	 */
	public final java.lang.Integer getsum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.sum.toString());
	}

	/**
	 * Set value of sum
	 * @param sum
	 */
	public final void setsum(java.lang.Integer sum)
	{
		setsum(getContext(), sum);
	}

	/**
	 * Set value of sum
	 * @param context
	 * @param sum
	 */
	public final void setsum(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sum)
	{
		getMendixObject().setValue(context, MemberNames.sum.toString(), sum);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Total_Transaction_transaction
	 */
	public final cinema.proxies.transaction getTotal_Transaction_transaction() throws com.mendix.core.CoreException
	{
		return getTotal_Transaction_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of Total_Transaction_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.transaction getTotal_Transaction_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Total_Transaction_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.transaction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Total_Transaction_transaction
	 * @param total_transaction_transaction
	 */
	public final void setTotal_Transaction_transaction(cinema.proxies.transaction total_transaction_transaction)
	{
		setTotal_Transaction_transaction(getContext(), total_transaction_transaction);
	}

	/**
	 * Set value of Total_Transaction_transaction
	 * @param context
	 * @param total_transaction_transaction
	 */
	public final void setTotal_Transaction_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.transaction total_transaction_transaction)
	{
		if (total_transaction_transaction == null) {
			getMendixObject().setValue(context, MemberNames.Total_Transaction_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Total_Transaction_transaction.toString(), total_transaction_transaction.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return total_TransactionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.Total_Transaction that = (cinema.proxies.Total_Transaction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
