// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class transaction
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.transaction";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TransCode("TransCode"),
		TransactionDate("TransactionDate"),
		Quantity("Quantity"),
		SubTotal("SubTotal"),
		TotalPrice("TotalPrice"),
		Status("Status"),
		lastChange("lastChange"),
		isLatest("isLatest"),
		transaction_Cinema("Cinema.transaction_Cinema"),
		transaction_PaymentMethod("Cinema.transaction_PaymentMethod"),
		PaymentActivity_transaction("Cinema.PaymentActivity_transaction"),
		TransactionDocumentUser_transaction("Cinema.TransactionDocumentUser_transaction"),
		transaction_PPN("Cinema.transaction_PPN"),
		transaction_User("Cinema.transaction_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public transaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected transaction(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionMendixObject)
	{
		if (transactionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionMendixObject = transactionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'transaction.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.transaction.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.transaction initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.transaction(context, mendixObject);
	}

	public static cinema.proxies.transaction load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.transaction.initialize(context, mendixObject);
	}

	public static java.util.List<cinema.proxies.transaction> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cinema.proxies.transaction.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TransCode
	 */
	public final java.lang.String getTransCode()
	{
		return getTransCode(getContext());
	}

	/**
	 * @param context
	 * @return value of TransCode
	 */
	public final java.lang.String getTransCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TransCode.toString());
	}

	/**
	 * Set value of TransCode
	 * @param transcode
	 */
	public final void setTransCode(java.lang.String transcode)
	{
		setTransCode(getContext(), transcode);
	}

	/**
	 * Set value of TransCode
	 * @param context
	 * @param transcode
	 */
	public final void setTransCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transcode)
	{
		getMendixObject().setValue(context, MemberNames.TransCode.toString(), transcode);
	}

	/**
	 * @return value of TransactionDate
	 */
	public final java.util.Date getTransactionDate()
	{
		return getTransactionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionDate
	 */
	public final java.util.Date getTransactionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TransactionDate.toString());
	}

	/**
	 * Set value of TransactionDate
	 * @param transactiondate
	 */
	public final void setTransactionDate(java.util.Date transactiondate)
	{
		setTransactionDate(getContext(), transactiondate);
	}

	/**
	 * Set value of TransactionDate
	 * @param context
	 * @param transactiondate
	 */
	public final void setTransactionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date transactiondate)
	{
		getMendixObject().setValue(context, MemberNames.TransactionDate.toString(), transactiondate);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.lang.Integer getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.lang.Integer quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of SubTotal
	 */
	public final java.lang.Integer getSubTotal()
	{
		return getSubTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of SubTotal
	 */
	public final java.lang.Integer getSubTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SubTotal.toString());
	}

	/**
	 * Set value of SubTotal
	 * @param subtotal
	 */
	public final void setSubTotal(java.lang.Integer subtotal)
	{
		setSubTotal(getContext(), subtotal);
	}

	/**
	 * Set value of SubTotal
	 * @param context
	 * @param subtotal
	 */
	public final void setSubTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer subtotal)
	{
		getMendixObject().setValue(context, MemberNames.SubTotal.toString(), subtotal);
	}

	/**
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice()
	{
		return getTotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPrice.toString());
	}

	/**
	 * Set value of TotalPrice
	 * @param totalprice
	 */
	public final void setTotalPrice(java.math.BigDecimal totalprice)
	{
		setTotalPrice(getContext(), totalprice);
	}

	/**
	 * Set value of TotalPrice
	 * @param context
	 * @param totalprice
	 */
	public final void setTotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalprice)
	{
		getMendixObject().setValue(context, MemberNames.TotalPrice.toString(), totalprice);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final cinema.proxies.Enum_StatusTrans getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final cinema.proxies.Enum_StatusTrans getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.Enum_StatusTrans.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(cinema.proxies.Enum_StatusTrans status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Enum_StatusTrans status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of lastChange
	 */
	public final java.util.Date getlastChange()
	{
		return getlastChange(getContext());
	}

	/**
	 * @param context
	 * @return value of lastChange
	 */
	public final java.util.Date getlastChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.lastChange.toString());
	}

	/**
	 * Set value of lastChange
	 * @param lastchange
	 */
	public final void setlastChange(java.util.Date lastchange)
	{
		setlastChange(getContext(), lastchange);
	}

	/**
	 * Set value of lastChange
	 * @param context
	 * @param lastchange
	 */
	public final void setlastChange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastchange)
	{
		getMendixObject().setValue(context, MemberNames.lastChange.toString(), lastchange);
	}

	/**
	 * @return value of isLatest
	 */
	public final java.lang.Boolean getisLatest()
	{
		return getisLatest(getContext());
	}

	/**
	 * @param context
	 * @return value of isLatest
	 */
	public final java.lang.Boolean getisLatest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isLatest.toString());
	}

	/**
	 * Set value of isLatest
	 * @param islatest
	 */
	public final void setisLatest(java.lang.Boolean islatest)
	{
		setisLatest(getContext(), islatest);
	}

	/**
	 * Set value of isLatest
	 * @param context
	 * @param islatest
	 */
	public final void setisLatest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islatest)
	{
		getMendixObject().setValue(context, MemberNames.isLatest.toString(), islatest);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of transaction_Cinema
	 */
	public final cinema.proxies.Cinema gettransaction_Cinema() throws com.mendix.core.CoreException
	{
		return gettransaction_Cinema(getContext());
	}

	/**
	 * @param context
	 * @return value of transaction_Cinema
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.Cinema gettransaction_Cinema(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.Cinema result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.transaction_Cinema.toString());
		if (identifier != null) {
			result = cinema.proxies.Cinema.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of transaction_Cinema
	 * @param transaction_cinema
	 */
	public final void settransaction_Cinema(cinema.proxies.Cinema transaction_cinema)
	{
		settransaction_Cinema(getContext(), transaction_cinema);
	}

	/**
	 * Set value of transaction_Cinema
	 * @param context
	 * @param transaction_cinema
	 */
	public final void settransaction_Cinema(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Cinema transaction_cinema)
	{
		if (transaction_cinema == null) {
			getMendixObject().setValue(context, MemberNames.transaction_Cinema.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.transaction_Cinema.toString(), transaction_cinema.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of transaction_PaymentMethod
	 */
	public final cinema.proxies.PaymentMethod gettransaction_PaymentMethod() throws com.mendix.core.CoreException
	{
		return gettransaction_PaymentMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of transaction_PaymentMethod
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.PaymentMethod gettransaction_PaymentMethod(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.PaymentMethod result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.transaction_PaymentMethod.toString());
		if (identifier != null) {
			result = cinema.proxies.PaymentMethod.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of transaction_PaymentMethod
	 * @param transaction_paymentmethod
	 */
	public final void settransaction_PaymentMethod(cinema.proxies.PaymentMethod transaction_paymentmethod)
	{
		settransaction_PaymentMethod(getContext(), transaction_paymentmethod);
	}

	/**
	 * Set value of transaction_PaymentMethod
	 * @param context
	 * @param transaction_paymentmethod
	 */
	public final void settransaction_PaymentMethod(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.PaymentMethod transaction_paymentmethod)
	{
		if (transaction_paymentmethod == null) {
			getMendixObject().setValue(context, MemberNames.transaction_PaymentMethod.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.transaction_PaymentMethod.toString(), transaction_paymentmethod.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PaymentActivity_transaction
	 */
	public final cinema.proxies.PaymentActivity getPaymentActivity_transaction() throws com.mendix.core.CoreException
	{
		return getPaymentActivity_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentActivity_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.PaymentActivity getPaymentActivity_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.PaymentActivity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PaymentActivity_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.PaymentActivity.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PaymentActivity_transaction
	 * @param paymentactivity_transaction
	 */
	public final void setPaymentActivity_transaction(cinema.proxies.PaymentActivity paymentactivity_transaction)
	{
		setPaymentActivity_transaction(getContext(), paymentactivity_transaction);
	}

	/**
	 * Set value of PaymentActivity_transaction
	 * @param context
	 * @param paymentactivity_transaction
	 */
	public final void setPaymentActivity_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.PaymentActivity paymentactivity_transaction)
	{
		if (paymentactivity_transaction == null) {
			getMendixObject().setValue(context, MemberNames.PaymentActivity_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentActivity_transaction.toString(), paymentactivity_transaction.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionDocumentUser_transaction
	 */
	public final cinema.proxies.TransactionDocumentUser getTransactionDocumentUser_transaction() throws com.mendix.core.CoreException
	{
		return getTransactionDocumentUser_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionDocumentUser_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.TransactionDocumentUser getTransactionDocumentUser_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.TransactionDocumentUser result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionDocumentUser_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.TransactionDocumentUser.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionDocumentUser_transaction
	 * @param transactiondocumentuser_transaction
	 */
	public final void setTransactionDocumentUser_transaction(cinema.proxies.TransactionDocumentUser transactiondocumentuser_transaction)
	{
		setTransactionDocumentUser_transaction(getContext(), transactiondocumentuser_transaction);
	}

	/**
	 * Set value of TransactionDocumentUser_transaction
	 * @param context
	 * @param transactiondocumentuser_transaction
	 */
	public final void setTransactionDocumentUser_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.TransactionDocumentUser transactiondocumentuser_transaction)
	{
		if (transactiondocumentuser_transaction == null) {
			getMendixObject().setValue(context, MemberNames.TransactionDocumentUser_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionDocumentUser_transaction.toString(), transactiondocumentuser_transaction.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of transaction_PPN
	 */
	public final cinema.proxies.PPN gettransaction_PPN() throws com.mendix.core.CoreException
	{
		return gettransaction_PPN(getContext());
	}

	/**
	 * @param context
	 * @return value of transaction_PPN
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.PPN gettransaction_PPN(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.PPN result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.transaction_PPN.toString());
		if (identifier != null) {
			result = cinema.proxies.PPN.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of transaction_PPN
	 * @param transaction_ppn
	 */
	public final void settransaction_PPN(cinema.proxies.PPN transaction_ppn)
	{
		settransaction_PPN(getContext(), transaction_ppn);
	}

	/**
	 * Set value of transaction_PPN
	 * @param context
	 * @param transaction_ppn
	 */
	public final void settransaction_PPN(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.PPN transaction_ppn)
	{
		if (transaction_ppn == null) {
			getMendixObject().setValue(context, MemberNames.transaction_PPN.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.transaction_PPN.toString(), transaction_ppn.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of transaction_User
	 */
	public final system.proxies.User gettransaction_User() throws com.mendix.core.CoreException
	{
		return gettransaction_User(getContext());
	}

	/**
	 * @param context
	 * @return value of transaction_User
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User gettransaction_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.transaction_User.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of transaction_User
	 * @param transaction_user
	 */
	public final void settransaction_User(system.proxies.User transaction_user)
	{
		settransaction_User(getContext(), transaction_user);
	}

	/**
	 * Set value of transaction_User
	 * @param context
	 * @param transaction_user
	 */
	public final void settransaction_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User transaction_user)
	{
		if (transaction_user == null) {
			getMendixObject().setValue(context, MemberNames.transaction_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.transaction_User.toString(), transaction_user.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.transaction that = (cinema.proxies.transaction) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
