// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class transactionhelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionhelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.transactionhelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TransCode("TransCode"),
		Status("Status"),
		TransactionDate("TransactionDate"),
		TicketTotal("TicketTotal"),
		lastChange("lastChange"),
		transactionhelper_transaction("Cinema.transactionhelper_transaction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public transactionhelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected transactionhelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionhelperMendixObject)
	{
		if (transactionhelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionhelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionhelperMendixObject = transactionhelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'transactionhelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.transactionhelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.transactionhelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.transactionhelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.transactionhelper(context, mendixObject);
	}

	public static cinema.proxies.transactionhelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.transactionhelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TransCode
	 */
	public final java.lang.String getTransCode()
	{
		return getTransCode(getContext());
	}

	/**
	 * @param context
	 * @return value of TransCode
	 */
	public final java.lang.String getTransCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TransCode.toString());
	}

	/**
	 * Set value of TransCode
	 * @param transcode
	 */
	public final void setTransCode(java.lang.String transcode)
	{
		setTransCode(getContext(), transcode);
	}

	/**
	 * Set value of TransCode
	 * @param context
	 * @param transcode
	 */
	public final void setTransCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String transcode)
	{
		getMendixObject().setValue(context, MemberNames.TransCode.toString(), transcode);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final cinema.proxies.Enum_StatusTrans getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final cinema.proxies.Enum_StatusTrans getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.Enum_StatusTrans.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(cinema.proxies.Enum_StatusTrans status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Enum_StatusTrans status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of TransactionDate
	 */
	public final java.util.Date getTransactionDate()
	{
		return getTransactionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionDate
	 */
	public final java.util.Date getTransactionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TransactionDate.toString());
	}

	/**
	 * Set value of TransactionDate
	 * @param transactiondate
	 */
	public final void setTransactionDate(java.util.Date transactiondate)
	{
		setTransactionDate(getContext(), transactiondate);
	}

	/**
	 * Set value of TransactionDate
	 * @param context
	 * @param transactiondate
	 */
	public final void setTransactionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date transactiondate)
	{
		getMendixObject().setValue(context, MemberNames.TransactionDate.toString(), transactiondate);
	}

	/**
	 * @return value of TicketTotal
	 */
	public final java.lang.Integer getTicketTotal()
	{
		return getTicketTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of TicketTotal
	 */
	public final java.lang.Integer getTicketTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TicketTotal.toString());
	}

	/**
	 * Set value of TicketTotal
	 * @param tickettotal
	 */
	public final void setTicketTotal(java.lang.Integer tickettotal)
	{
		setTicketTotal(getContext(), tickettotal);
	}

	/**
	 * Set value of TicketTotal
	 * @param context
	 * @param tickettotal
	 */
	public final void setTicketTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tickettotal)
	{
		getMendixObject().setValue(context, MemberNames.TicketTotal.toString(), tickettotal);
	}

	/**
	 * @return value of lastChange
	 */
	public final java.util.Date getlastChange()
	{
		return getlastChange(getContext());
	}

	/**
	 * @param context
	 * @return value of lastChange
	 */
	public final java.util.Date getlastChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.lastChange.toString());
	}

	/**
	 * Set value of lastChange
	 * @param lastchange
	 */
	public final void setlastChange(java.util.Date lastchange)
	{
		setlastChange(getContext(), lastchange);
	}

	/**
	 * Set value of lastChange
	 * @param context
	 * @param lastchange
	 */
	public final void setlastChange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastchange)
	{
		getMendixObject().setValue(context, MemberNames.lastChange.toString(), lastchange);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of transactionhelper_transaction
	 */
	public final cinema.proxies.transaction gettransactionhelper_transaction() throws com.mendix.core.CoreException
	{
		return gettransactionhelper_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of transactionhelper_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.transaction gettransactionhelper_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.transactionhelper_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.transaction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of transactionhelper_transaction
	 * @param transactionhelper_transaction
	 */
	public final void settransactionhelper_transaction(cinema.proxies.transaction transactionhelper_transaction)
	{
		settransactionhelper_transaction(getContext(), transactionhelper_transaction);
	}

	/**
	 * Set value of transactionhelper_transaction
	 * @param context
	 * @param transactionhelper_transaction
	 */
	public final void settransactionhelper_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.transaction transactionhelper_transaction)
	{
		if (transactionhelper_transaction == null) {
			getMendixObject().setValue(context, MemberNames.transactionhelper_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.transactionhelper_transaction.toString(), transactionhelper_transaction.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionhelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.transactionhelper that = (cinema.proxies.transactionhelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
