// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class TransactionDocumentUser extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.TransactionDocumentUser";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DocumentTypeUser("DocumentTypeUser"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		TransactionDocumentUser_transaction("Cinema.TransactionDocumentUser_transaction");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransactionDocumentUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TransactionDocumentUser(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionDocumentUserMendixObject)
	{
		super(context, transactionDocumentUserMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionDocumentUserMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'TransactionDocumentUser.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.TransactionDocumentUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.TransactionDocumentUser.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.TransactionDocumentUser initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.TransactionDocumentUser(context, mendixObject);
	}

	public static cinema.proxies.TransactionDocumentUser load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.TransactionDocumentUser.initialize(context, mendixObject);
	}

	public static java.util.List<cinema.proxies.TransactionDocumentUser> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cinema.proxies.TransactionDocumentUser.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Set value of DocumentTypeUser
	 * @param documenttypeuser
	 */
	public final cinema.proxies.Enum_DocumentType getDocumentTypeUser()
	{
		return getDocumentTypeUser(getContext());
	}

	/**
	 * @param context
	 * @return value of DocumentTypeUser
	 */
	public final cinema.proxies.Enum_DocumentType getDocumentTypeUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DocumentTypeUser.toString());
		if (obj == null) {
			return null;
		}
		return cinema.proxies.Enum_DocumentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DocumentTypeUser
	 * @param documenttypeuser
	 */
	public final void setDocumentTypeUser(cinema.proxies.Enum_DocumentType documenttypeuser)
	{
		setDocumentTypeUser(getContext(), documenttypeuser);
	}

	/**
	 * Set value of DocumentTypeUser
	 * @param context
	 * @param documenttypeuser
	 */
	public final void setDocumentTypeUser(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.Enum_DocumentType documenttypeuser)
	{
		if (documenttypeuser != null) {
			getMendixObject().setValue(context, MemberNames.DocumentTypeUser.toString(), documenttypeuser.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DocumentTypeUser.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionDocumentUser_transaction
	 */
	public final cinema.proxies.transaction getTransactionDocumentUser_transaction() throws com.mendix.core.CoreException
	{
		return getTransactionDocumentUser_transaction(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionDocumentUser_transaction
	 * @throws com.mendix.core.CoreException
	 */
	public final cinema.proxies.transaction getTransactionDocumentUser_transaction(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cinema.proxies.transaction result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionDocumentUser_transaction.toString());
		if (identifier != null) {
			result = cinema.proxies.transaction.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionDocumentUser_transaction
	 * @param transactiondocumentuser_transaction
	 */
	public final void setTransactionDocumentUser_transaction(cinema.proxies.transaction transactiondocumentuser_transaction)
	{
		setTransactionDocumentUser_transaction(getContext(), transactiondocumentuser_transaction);
	}

	/**
	 * Set value of TransactionDocumentUser_transaction
	 * @param context
	 * @param transactiondocumentuser_transaction
	 */
	public final void setTransactionDocumentUser_transaction(com.mendix.systemwideinterfaces.core.IContext context, cinema.proxies.transaction transactiondocumentuser_transaction)
	{
		if (transactiondocumentuser_transaction == null) {
			getMendixObject().setValue(context, MemberNames.TransactionDocumentUser_transaction.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionDocumentUser_transaction.toString(), transactiondocumentuser_transaction.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.TransactionDocumentUser that = (cinema.proxies.TransactionDocumentUser) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
