// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cinema.proxies;

public class TransactionCSV
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionCSVMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Cinema.TransactionCSV";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CO1_TransCode("CO1_TransCode"),
		CO2_TransDate("CO2_TransDate"),
		CO3_Quantity("CO3_Quantity"),
		CO4_SubTotal("CO4_SubTotal"),
		CO5_TotalPrice("CO5_TotalPrice"),
		CO6_Status("CO6_Status"),
		CO7_LastChange("CO7_LastChange"),
		CO8_isLatest("CO8_isLatest"),
		CO9_PpnReference("CO9_PpnReference"),
		CO10_PaymentMethodReference("CO10_PaymentMethodReference"),
		CO11_CinemaReference("CO11_CinemaReference"),
		CO12_UserReference("CO12_UserReference");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransactionCSV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TransactionCSV(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionCSVMendixObject)
	{
		if (transactionCSVMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionCSVMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionCSVMendixObject = transactionCSVMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransactionCSV.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static cinema.proxies.TransactionCSV initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return cinema.proxies.TransactionCSV.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cinema.proxies.TransactionCSV initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cinema.proxies.TransactionCSV(context, mendixObject);
	}

	public static cinema.proxies.TransactionCSV load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cinema.proxies.TransactionCSV.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CO1_TransCode
	 */
	public final java.lang.String getCO1_TransCode()
	{
		return getCO1_TransCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CO1_TransCode
	 */
	public final java.lang.String getCO1_TransCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO1_TransCode.toString());
	}

	/**
	 * Set value of CO1_TransCode
	 * @param co1_transcode
	 */
	public final void setCO1_TransCode(java.lang.String co1_transcode)
	{
		setCO1_TransCode(getContext(), co1_transcode);
	}

	/**
	 * Set value of CO1_TransCode
	 * @param context
	 * @param co1_transcode
	 */
	public final void setCO1_TransCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co1_transcode)
	{
		getMendixObject().setValue(context, MemberNames.CO1_TransCode.toString(), co1_transcode);
	}

	/**
	 * @return value of CO2_TransDate
	 */
	public final java.lang.String getCO2_TransDate()
	{
		return getCO2_TransDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CO2_TransDate
	 */
	public final java.lang.String getCO2_TransDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO2_TransDate.toString());
	}

	/**
	 * Set value of CO2_TransDate
	 * @param co2_transdate
	 */
	public final void setCO2_TransDate(java.lang.String co2_transdate)
	{
		setCO2_TransDate(getContext(), co2_transdate);
	}

	/**
	 * Set value of CO2_TransDate
	 * @param context
	 * @param co2_transdate
	 */
	public final void setCO2_TransDate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co2_transdate)
	{
		getMendixObject().setValue(context, MemberNames.CO2_TransDate.toString(), co2_transdate);
	}

	/**
	 * @return value of CO3_Quantity
	 */
	public final java.lang.String getCO3_Quantity()
	{
		return getCO3_Quantity(getContext());
	}

	/**
	 * @param context
	 * @return value of CO3_Quantity
	 */
	public final java.lang.String getCO3_Quantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO3_Quantity.toString());
	}

	/**
	 * Set value of CO3_Quantity
	 * @param co3_quantity
	 */
	public final void setCO3_Quantity(java.lang.String co3_quantity)
	{
		setCO3_Quantity(getContext(), co3_quantity);
	}

	/**
	 * Set value of CO3_Quantity
	 * @param context
	 * @param co3_quantity
	 */
	public final void setCO3_Quantity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co3_quantity)
	{
		getMendixObject().setValue(context, MemberNames.CO3_Quantity.toString(), co3_quantity);
	}

	/**
	 * @return value of CO4_SubTotal
	 */
	public final java.lang.String getCO4_SubTotal()
	{
		return getCO4_SubTotal(getContext());
	}

	/**
	 * @param context
	 * @return value of CO4_SubTotal
	 */
	public final java.lang.String getCO4_SubTotal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO4_SubTotal.toString());
	}

	/**
	 * Set value of CO4_SubTotal
	 * @param co4_subtotal
	 */
	public final void setCO4_SubTotal(java.lang.String co4_subtotal)
	{
		setCO4_SubTotal(getContext(), co4_subtotal);
	}

	/**
	 * Set value of CO4_SubTotal
	 * @param context
	 * @param co4_subtotal
	 */
	public final void setCO4_SubTotal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co4_subtotal)
	{
		getMendixObject().setValue(context, MemberNames.CO4_SubTotal.toString(), co4_subtotal);
	}

	/**
	 * @return value of CO5_TotalPrice
	 */
	public final java.lang.String getCO5_TotalPrice()
	{
		return getCO5_TotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of CO5_TotalPrice
	 */
	public final java.lang.String getCO5_TotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO5_TotalPrice.toString());
	}

	/**
	 * Set value of CO5_TotalPrice
	 * @param co5_totalprice
	 */
	public final void setCO5_TotalPrice(java.lang.String co5_totalprice)
	{
		setCO5_TotalPrice(getContext(), co5_totalprice);
	}

	/**
	 * Set value of CO5_TotalPrice
	 * @param context
	 * @param co5_totalprice
	 */
	public final void setCO5_TotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co5_totalprice)
	{
		getMendixObject().setValue(context, MemberNames.CO5_TotalPrice.toString(), co5_totalprice);
	}

	/**
	 * @return value of CO6_Status
	 */
	public final java.lang.String getCO6_Status()
	{
		return getCO6_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of CO6_Status
	 */
	public final java.lang.String getCO6_Status(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO6_Status.toString());
	}

	/**
	 * Set value of CO6_Status
	 * @param co6_status
	 */
	public final void setCO6_Status(java.lang.String co6_status)
	{
		setCO6_Status(getContext(), co6_status);
	}

	/**
	 * Set value of CO6_Status
	 * @param context
	 * @param co6_status
	 */
	public final void setCO6_Status(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co6_status)
	{
		getMendixObject().setValue(context, MemberNames.CO6_Status.toString(), co6_status);
	}

	/**
	 * @return value of CO7_LastChange
	 */
	public final java.lang.String getCO7_LastChange()
	{
		return getCO7_LastChange(getContext());
	}

	/**
	 * @param context
	 * @return value of CO7_LastChange
	 */
	public final java.lang.String getCO7_LastChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO7_LastChange.toString());
	}

	/**
	 * Set value of CO7_LastChange
	 * @param co7_lastchange
	 */
	public final void setCO7_LastChange(java.lang.String co7_lastchange)
	{
		setCO7_LastChange(getContext(), co7_lastchange);
	}

	/**
	 * Set value of CO7_LastChange
	 * @param context
	 * @param co7_lastchange
	 */
	public final void setCO7_LastChange(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co7_lastchange)
	{
		getMendixObject().setValue(context, MemberNames.CO7_LastChange.toString(), co7_lastchange);
	}

	/**
	 * @return value of CO8_isLatest
	 */
	public final java.lang.String getCO8_isLatest()
	{
		return getCO8_isLatest(getContext());
	}

	/**
	 * @param context
	 * @return value of CO8_isLatest
	 */
	public final java.lang.String getCO8_isLatest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO8_isLatest.toString());
	}

	/**
	 * Set value of CO8_isLatest
	 * @param co8_islatest
	 */
	public final void setCO8_isLatest(java.lang.String co8_islatest)
	{
		setCO8_isLatest(getContext(), co8_islatest);
	}

	/**
	 * Set value of CO8_isLatest
	 * @param context
	 * @param co8_islatest
	 */
	public final void setCO8_isLatest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co8_islatest)
	{
		getMendixObject().setValue(context, MemberNames.CO8_isLatest.toString(), co8_islatest);
	}

	/**
	 * @return value of CO9_PpnReference
	 */
	public final java.lang.String getCO9_PpnReference()
	{
		return getCO9_PpnReference(getContext());
	}

	/**
	 * @param context
	 * @return value of CO9_PpnReference
	 */
	public final java.lang.String getCO9_PpnReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO9_PpnReference.toString());
	}

	/**
	 * Set value of CO9_PpnReference
	 * @param co9_ppnreference
	 */
	public final void setCO9_PpnReference(java.lang.String co9_ppnreference)
	{
		setCO9_PpnReference(getContext(), co9_ppnreference);
	}

	/**
	 * Set value of CO9_PpnReference
	 * @param context
	 * @param co9_ppnreference
	 */
	public final void setCO9_PpnReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co9_ppnreference)
	{
		getMendixObject().setValue(context, MemberNames.CO9_PpnReference.toString(), co9_ppnreference);
	}

	/**
	 * @return value of CO10_PaymentMethodReference
	 */
	public final java.lang.String getCO10_PaymentMethodReference()
	{
		return getCO10_PaymentMethodReference(getContext());
	}

	/**
	 * @param context
	 * @return value of CO10_PaymentMethodReference
	 */
	public final java.lang.String getCO10_PaymentMethodReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO10_PaymentMethodReference.toString());
	}

	/**
	 * Set value of CO10_PaymentMethodReference
	 * @param co10_paymentmethodreference
	 */
	public final void setCO10_PaymentMethodReference(java.lang.String co10_paymentmethodreference)
	{
		setCO10_PaymentMethodReference(getContext(), co10_paymentmethodreference);
	}

	/**
	 * Set value of CO10_PaymentMethodReference
	 * @param context
	 * @param co10_paymentmethodreference
	 */
	public final void setCO10_PaymentMethodReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co10_paymentmethodreference)
	{
		getMendixObject().setValue(context, MemberNames.CO10_PaymentMethodReference.toString(), co10_paymentmethodreference);
	}

	/**
	 * @return value of CO11_CinemaReference
	 */
	public final java.lang.String getCO11_CinemaReference()
	{
		return getCO11_CinemaReference(getContext());
	}

	/**
	 * @param context
	 * @return value of CO11_CinemaReference
	 */
	public final java.lang.String getCO11_CinemaReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO11_CinemaReference.toString());
	}

	/**
	 * Set value of CO11_CinemaReference
	 * @param co11_cinemareference
	 */
	public final void setCO11_CinemaReference(java.lang.String co11_cinemareference)
	{
		setCO11_CinemaReference(getContext(), co11_cinemareference);
	}

	/**
	 * Set value of CO11_CinemaReference
	 * @param context
	 * @param co11_cinemareference
	 */
	public final void setCO11_CinemaReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co11_cinemareference)
	{
		getMendixObject().setValue(context, MemberNames.CO11_CinemaReference.toString(), co11_cinemareference);
	}

	/**
	 * @return value of CO12_UserReference
	 */
	public final java.lang.String getCO12_UserReference()
	{
		return getCO12_UserReference(getContext());
	}

	/**
	 * @param context
	 * @return value of CO12_UserReference
	 */
	public final java.lang.String getCO12_UserReference(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CO12_UserReference.toString());
	}

	/**
	 * Set value of CO12_UserReference
	 * @param co12_userreference
	 */
	public final void setCO12_UserReference(java.lang.String co12_userreference)
	{
		setCO12_UserReference(getContext(), co12_userreference);
	}

	/**
	 * Set value of CO12_UserReference
	 * @param context
	 * @param co12_userreference
	 */
	public final void setCO12_UserReference(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String co12_userreference)
	{
		getMendixObject().setValue(context, MemberNames.CO12_UserReference.toString(), co12_userreference);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionCSVMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cinema.proxies.TransactionCSV that = (cinema.proxies.TransactionCSV) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
